### ISSUE TITLE
virustotal on hdr_toggle.exe

### ISSUE THREAD

**Issue by Alex-sConjecture** [nitschis/hdr_toggle#1]
you may want to address virustotal report on a latest release executable... maybe by providing additional explanation or changing how its packaged?
thanks!

https://www.virustotal.com/gui/file/8d131c6ac8e4e173532c2656d173c05ff497c58a2ff31525834189bb4f312318/detection

**Comment by nitschis** [comment]
Thanks for the hint. I guess they don't like compiled vbs hotkeys. Nothing really I can do about it, as you can see, it is mostly "ML" suspicions.

The only thing I can think of is scrambling / cryping it so AV don't see it. But that is actually a practice Virus, Trojan, RAT creators use to hide their malicious code...

I am open to suggestions. If you are skeptical, all you need to do is run the command in the readme. The "code" is very simple and understandable for everyone.

**Comment by Alex-sConjecture** [comment]
Don’t get me wrong.. not skeptical at all. I just thought it would be
useful to make a comment for some folks who may mistakenly think that there
is something wrong. I use it and I like it!

**Comment by nitschis** [comment]
Oh, I understand. Thanks for the hint. I will think about adding a comment to the README about it. Glad at least someone got some use out of it!
